# Generated by Django 3.2.4 on 2021-10-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
