# Generated by Django 3.2.4 on 2021-10-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211018_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
